kind: Deployment
apiVersion: apps/v1
metadata:
    name: sport-chirp-frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: sport-chirp-frontend
    template:
        metadata:
            labels:
                app: sport-chirp-frontend
        spec:
            containers:
                - name: sport-chirp-frontend
                  image: localhost:5000/sport-chirp-frontend
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 80
            restartPolicy: Always